version: "3"

services:
  main:
    build:
      context: .
      dockerfile: main_Dockerfile
    expose: 
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - react
    container_name: my_main_container
    networks:
      - custom_network

  react:
    build:
      context: ./final-product
      dockerfile: react_Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    container_name: my_react_container
    networks:
      - custom_network

networks:
  custom_network:
    name: test_network
    driver: bridge